### PR TITLE
Upgrade controller-runtime to v0.24.0

### LINKED ISSUE #32: Some projects importing both `cli-utils` and `controller-runtime` cannot build on `cli-utils@v1.1.0`
xref: https://github.com/kubernetes-sigs/controller-runtime/issues/3508

Since `cli-utils@v1.1.0` is importing Kubernetes 1.36 but latest `controller-runtime` is not, I'm seeing errors like this:

```
# sigs.k8s.io/controller-runtime/pkg/cache
Error: ../../../go/pkg/mod/sigs.k8s.io/controller-runtime@v0.23.3/pkg/cache/multi_namespace_cache.go:363:9: cannot use handles (variable of struct type handlerRegistration) as "k8s.io/client-go/tools/cache".ResourceEventHandlerRegistration value in return statement: handlerRegistration does not implement "k8s.io/client-go/tools/cache".ResourceEventHandlerRegistration (missing method HasSyncedChecker)
Error: ../../../go/pkg/mod/sigs.k8s.io/controller-runtime@v0.23.3/pkg/cache/multi_namespace_cache.go:380:9: cannot use handles (variable of struct type handlerRegistration) as "k8s.io/client-go/tools/cache".ResourceEventHandlerRegistration value in return statement: handlerRegistration does not implement "k8s.io/client-go/tools/cache".ResourceEventHandlerRegistration (missing method HasSyncedChecker)
Error: ../../../go/pkg/mod/sigs.k8s.io/controller-runtime@v0.23.3/pkg/cache/multi_namespace_cache.go:397:9: cannot use handles (variable of struct type handlerRegistration) as "k8s.io/client-go/tools/cache".ResourceEventHandlerRegistration value in return statement: handlerRegistration does not implement "k8s.io/client-go/tools/cache".ResourceEventHandlerRegistration (missing method HasSyncedChecker)
Error: ../../../go/pkg/mod/sigs.k8s.io/controller-runtime@v0.23.3/pkg/cache/multi_namespace_cache.go:402:17: impossible type assertion: h.(handlerRegistration)
	handlerRegistration does not implement "k8s.io/client-go/tools/cache".ResourceEventHandlerRegistration (missing method HasSyncedChecker)
```

Helm, for example, cannot upgrade:

https://github.com/helm/helm/blob/4bd9e90aa0ef29a1a7b4dfbd5234be785e846204/go.mod#L20-L51

I first saw this here:

https://github.com/matheuscscp/cloudflare-gateway-controller/actions/runs/24932296774/job/73011945305?pr=76

### PR DESCRIPTION
**Pull request by matheuscscp**
Depends on: https://github.com/kubernetes-sigs/controller-runtime/issues/3435

Closes: #32

xref: https://github.com/fluxcd/cli-utils/issues/32#issuecomment-4319856221

### CODE REVIEW

**Review by stefanprodan — APPROVED** [review]
LGTM 🚀
