### ISSUE TITLE
Some projects importing both `cli-utils` and `controller-runtime` cannot build on `cli-utils@v1.1.0`

### ISSUE THREAD

**Issue by matheuscscp** [fluxcd/cli-utils#32]
xref: https://github.com/kubernetes-sigs/controller-runtime/issues/3508

Since `cli-utils@v1.1.0` is importing Kubernetes 1.36 but latest `controller-runtime` is not, I'm seeing errors like this:

```
# sigs.k8s.io/controller-runtime/pkg/cache
Error: ../../../go/pkg/mod/sigs.k8s.io/controller-runtime@v0.23.3/pkg/cache/multi_namespace_cache.go:363:9: cannot use handles (variable of struct type handlerRegistration) as "k8s.io/client-go/tools/cache".ResourceEventHandlerRegistration value in return statement: handlerRegistration does not implement "k8s.io/client-go/tools/cache".ResourceEventHandlerRegistration (missing method HasSyncedChecker)
Error: ../../../go/pkg/mod/sigs.k8s.io/controller-runtime@v0.23.3/pkg/cache/multi_namespace_cache.go:380:9: cannot use handles (variable of struct type handlerRegistration) as "k8s.io/client-go/tools/cache".ResourceEventHandlerRegistration value in return statement: handlerRegistration does not implement "k8s.io/client-go/tools/cache".ResourceEventHandlerRegistration (missing method HasSyncedChecker)
Error: ../../../go/pkg/mod/sigs.k8s.io/controller-runtime@v0.23.3/pkg/cache/multi_namespace_cache.go:397:9: cannot use handles (variable of struct type handlerRegistration) as "k8s.io/client-go/tools/cache".ResourceEventHandlerRegistration value in return statement: handlerRegistration does not implement "k8s.io/client-go/tools/cache".ResourceEventHandlerRegistration (missing method HasSyncedChecker)
Error: ../../../go/pkg/mod/sigs.k8s.io/controller-runtime@v0.23.3/pkg/cache/multi_namespace_cache.go:402:17: impossible type assertion: h.(handlerRegistration)
	handlerRegistration does not implement "k8s.io/client-go/tools/cache".ResourceEventHandlerRegistration (missing method HasSyncedChecker)
```

Helm, for example, cannot upgrade:

https://github.com/helm/helm/blob/4bd9e90aa0ef29a1a7b4dfbd5234be785e846204/go.mod#L20-L51

I first saw this here:

https://github.com/matheuscscp/cloudflare-gateway-controller/actions/runs/24932296774/job/73011945305?pr=76

**Comment by stefanprodan** [comment]
Let’s add a dummy cmd and run build during CI to catch breaking changes like this in the future

**Comment by matheuscscp** [comment]
Looks like Helm builds, but needs several changes:

https://github.com/helm/helm/pull/32078

**Comment by matheuscscp** [comment]
> Looks like Helm builds, but needs several changes:
> 
> [helm/helm#32078](https://github.com/helm/helm/pull/32078)

This is Go building only the import graph. There's nothing in Helm importing the controller-runtime packages that were broken by Kubernetes 1.36.

**Comment by matheuscscp** [comment]
My PR upgrading Helm to Kubernetes 1.36 got merged
